version: '2'

services:

  discovery-server:
    image: dabuild/discovery-server:1.0-SNAPSHOT

  config-server:
    image: dabuild/config-server:1.0-SNAPSHOT
    links:
     - discovery-server

  repository:
    image: dabuild/repository:1.0-SNAPSHOT
    links:
     - config-server
     - discovery-server

  service:
    image: dabuild/service:1.0-SNAPSHOT
    links:
     - config-server
     - discovery-server

  #web:
  #  image: dabuild/web:1.0-SNAPSHOT
  #  links:
  #   - config-server
  #   - discovery-server

  webhook-api:
    image: dabuild/webhook-api:1.0-SNAPSHOT
    links:
     - config-server
     - discovery-server
