server:
  port: 8080
spring:
  application:
    name: dabuild-web
eureka:
  instance:
    hostname: localhost
    nonSecurePort: 8761
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2