server:
  port: ${PORT:8888}

eureka:
  instance:
    appname: ${spring.application.name}
    hostname: localhost
    nonSecurePort: 8761
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    config:
      server:
        git:
          uri: /tmp/dabuild-config
          basedir: .