server:
  port: ${PORT:8888}

eureka:
  instance:
    appname: ${spring.application.name}
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 10
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    config:
      server:
        git:
          uri: /tmp/dabuild-config
          basedir: .